server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: cloud-provider-service-8081

debug: true
