server:
  port: 80

spring:
  application:
    name: cloud-consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: cloud-consumer-service-80

debug: true
ribbon:
  ReadTimeout: 6000
  ConnectingTimeOut: 6000



